Repository andela/technites-bn-frontend, pull requests merged in 2019-11, with the labels that each got.

#6 #168049935 Update TravisCI to run tests
  .travis.yml
Labels: ready for review

#3 #168049936 Setup react router(React-router-dom)
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  public/barefoot-logo.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/assets/bare-foot-logo.png
  src/assets/barefoot-logo.png
  src/assets/barefoot-logo1.png
  src/assets/traveller.jpg
  src/components/App.js
  src/components/App.test.js
  src/components/Router.js
  src/components/index.js
  src/components/landingPage/LandingPage.js
  src/components/landingPage/LandingPage.scss
  src/components/loginPage/LoginPage.js
  src/components/notFound/NotFound.js
  src/components/topNav/TopNav.js
  src/components/topNav/TopNav.scss
  src/index.js
  src/logo.svg
  src/styles/App.css
  src/styles/index.css
  yarn.lock
Labels: Await TTL's approval

#9 #168049939 Create the client readme file
  .gitignore
  README.md
Labels: ready for review

#1 #169502703 Add sentry to log errors
  .eslintrc.json
  package.json
  src/App.js
  src/index.js
Labels: Await TTL's approval

#7 #168049933 Set up tests on the client
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/App.js
  src/components/App.js
  src/components/App.test.js
  src/components/Router.js
  src/components/__tests__/App.test.js
  src/components/index.js
  src/components/landing-page/LandingPage.js
  src/components/landing-page/LandingPage.scss
  src/components/login-page/LoginPage.js
  src/components/loginPage/LoginPage.js
  src/components/not-found/NotFound.js
  src/components/top-nav/TopNav.js
  src/components/top-nav/TopNav.scss
  src/index.js
Labels: ready for review

#5 #168049937 Setup SASS processing on the client
  package-lock.json
  src/App.js
  src/components/App.js
  src/index.js
  src/styles/App.scss
  src/styles/index.scss
Labels: ready for review

#8 #168049940 add storybook for react
  .storybook/addons.js
  .storybook/config.js
  package-lock.json
  package.json
  src/stories/0-Welcome.stories.js
  src/stories/1-Button.stories.js
Labels: ready for review

#4 #168049932 Setup redux
  package-lock.json
  package.json
  src/App.js
  src/components/App.js
  src/components/__tests__/App.test.js
  src/components/notifications-pane.jsx
  src/index.js
  src/redux/reducers/rootReducer.js
  src/redux/reducers/testReducer.js
  src/redux/store/configureStore.js
Labels: ready for review

#10 #169592274 Adds test coverage report configuration
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: ready for review

#11 #168049941 Users should be able Signup/Register to Barefoot Nomad
  .eslintrc.json
  package-lock.json
  package.json
  src/__tests__/actions/registerAction.test.js
  src/__tests__/components/protected-route/ProtectedRoute.test.js
  src/__tests__/components/register-page/registerPage.test.js
  src/__tests__/redux/reducers/registerReducer.test.js
  src/assets/verify.png
  src/components/App.js
  src/components/Router.js
  src/components/__tests__/App.test.js
  src/components/form/form.jsx
  src/components/form/form.scss
  src/components/index.js
  src/components/input/input.jsx
  src/components/input/input.scss
  src/components/landing-page/LandingPage.css
  src/components/landing-page/LandingPage.css.map
  src/components/landing-page/LandingPage.js
  src/components/navbar/navbar.jsx
  src/components/navbar/navbar.scss
  src/components/protected-route/ProtectedRoute.jsx
  src/components/register-page/RegisterPage.jsx
  src/components/register-page/VerifyEmail.jsx
  src/components/top-nav/TopNav.js
  src/components/top-nav/TopNav.scss
  src/redux/actions/actionType.jsx
  src/redux/actions/registerAction.jsx
  src/redux/reducers/registerReducer.jsx
  src/redux/reducers/rootReducer.js
  src/redux/store/configureStore.js
  src/redux/store/initialState.js
  src/services/authServices.js
  src/services/httpServices.js
  src/setupTests.js
  src/styles/App.css
  src/styles/App.css.map
  src/styles/index.css
  src/styles/index.css.map
Labels: ready for review

#12 #168049946 Implement requests table
  .circleci/config.yml
  package-lock.json
  package.json
  src/__mocks__/__get_user_request_failure__.json
  src/__mocks__/__get_user_request_success__.json
  src/__tests__/actions/UserRequestActions.test.js
  src/__tests__/components/user-requests/UserRequests.test.js
  src/__tests__/redux/ErrorReducer.test.js
  src/__tests__/redux/UserRequestsReducer.test.js
  src/components/Router.js
  src/components/index.js
  src/components/table/Table.scss
  src/components/table/index.js
  src/components/user-requests/UserRequests.js
  src/config/dbCall.js
  src/redux/actions/UserRequestActions.js
  src/redux/actions/actionType.jsx
  src/redux/reducers/ErrorReducer.js
  src/redux/reducers/UserRequestsReducer.js
  src/redux/reducers/rootReducer.js
  src/styles/_variables.scss
  src/styles/index.scss
  src/validation/IsEmpty.js
Labels: ready for review

#13 #168049943 Users should be able to Login to Barefoot Nomad
  package-lock.json
  package.json
  src/__mocks__/fixtures.js
  src/__tests__/components/App.test.js
  src/__tests__/components/login-page/LoginForm.test.js
  src/__tests__/components/login-page/LoginPage.test.js
  src/__tests__/components/login-page/SocialLogins.test.js
  src/__tests__/components/protected-route/ProtectedRoute.test.js
  src/__tests__/redux/actions/LoginAction.test.js
  src/__tests__/redux/actions/socialAuthAction.test.js
  src/__tests__/redux/reducers/loginReducer.test.js
  src/__tests__/redux/reducers/socialAuthReducer.test.js
  src/assets/images/socialMedia/facebook.svg
  src/assets/images/socialMedia/gmail.svg
  src/components/App.js
  src/components/Router.js
  src/components/dashboard/Dashboard.js
  src/components/form/form.jsx
  src/components/form/form.scss
  src/components/index.js
  src/components/landing-page/LandingPage.js
  src/components/login-page/LoginForm.js
  src/components/login-page/LoginPage.js
  src/components/login-page/SocialLogins.js
  src/components/login-page/login.scss
  src/components/navbar/navbar.jsx
  src/components/protected-route/ProtectedRoute.jsx
  src/components/register-page/RegisterPage.jsx
  src/components/top-nav/TopNav.css
  src/components/top-nav/TopNav.css.map
  src/redux/actions/actionType.jsx
  src/redux/actions/loginAction.jsx
  src/redux/actions/registerAction.jsx
  src/redux/actions/socialAuthAction.js
  src/redux/reducers/initialState.js
  src/redux/reducers/loginReducer.jsx
  src/redux/reducers/registerReducer.jsx
  src/redux/reducers/rootReducer.js
  src/redux/reducers/socialAuthReducer.js
  src/services/authServices.js
  src/services/history.js
  src/services/httpServices.js
Labels: ready for review

#14 Ft notification pane 168049948
  package-lock.json
  package.json
  src/__mocks__/fixtures.js
  src/__tests__/components/App.test.js
  src/__tests__/components/ProfilePage.test.js
  src/__tests__/components/admin-requests/AdminRequests.test.js
  src/__tests__/components/common/close-icon-button.test.js
  src/__tests__/components/home-nav/homeNav.test.js
  src/__tests__/components/login-page/LoginForm.test.js
  src/__tests__/components/notification/notificationPane.test.js
  src/__tests__/components/notification/singleNotification.test.js
  src/__tests__/components/user-requests/UserRequests.test.js
  src/__tests__/redux/actions/LoginAction.test.js
  src/__tests__/redux/actions/notificationAction.test.js
  src/__tests__/redux/reducers/notificationReducer.test.js
  src/components/App.js
  src/components/Router.js
  src/components/common/close-icon-button.jsx
  src/components/common/close-icon-button.scss
  src/components/dashboard/Dashboard.js
  src/components/home-nav/HomeNav.js
  src/components/home-nav/HomeNav.scss
  src/components/index.js
  src/components/login-page/LoginForm.js
  src/components/login-page/LoginPage.js
  src/components/login-page/SocialLogins.js
  src/components/notification/notidicationPane.scss
  src/components/notification/notificationModal.scss
  src/components/notification/notificationPane.jsx
  src/components/notification/singleNotification.jsx
  src/components/notifications-pane.jsx
  src/components/profile-page/ProfilePage.js
  src/components/protected-route/ProtectedRoute.jsx
  src/index.js
  src/redux/actions/actionType.jsx
  src/redux/actions/loginAction.jsx
  src/redux/actions/notificationActions.js
  src/redux/actions/profileAction.js
  src/redux/reducers/ErrorReducer.js
  src/redux/reducers/initialState.js
  src/redux/reducers/notificationReducer.js
  src/redux/reducers/rootReducer.js
  src/services/authServices.js
  src/services/httpServices.js
  src/services/notificationServices.js
  src/setupTests.js
  src/styles/index.scss
Labels: ready for review

#21 #168049942 password reset
  package-lock.json
  package.json
  src/__tests__/components/common/close-icon-button.test.js
  src/__tests__/components/login-page/SocialLogins.test.js
  src/__tests__/components/passwordReset/forgotEmailForm.test.js
  src/__tests__/components/passwordReset/passwordResetConfirmation.test.js
  src/__tests__/components/passwordReset/resetPassword.test.js
  src/__tests__/redux/actions/passwordResetAction.test.js
  src/__tests__/redux/reducers/passwordResetReducer.test.js
  src/components/Router.js
  src/components/index.js
  src/components/passwordReset/forgotEmailForm.jsx
  src/components/passwordReset/passwordReset.scss
  src/components/passwordReset/passwordResetConfirmation.jsx
  src/components/passwordReset/resetPassword.jsx
  src/redux/actions/actionType.jsx
  src/redux/actions/passwordResetAction.js
  src/redux/reducers/PasswordResetReducer.js
  src/redux/reducers/initialState.js
  src/redux/reducers/rootReducer.js
  src/services/authServices.js
  src/styles/index.scss
Labels: ready for review

#23 #168049949 Implement requests page main panel header
  src/__tests__/components/admin-requests/AdminRequests.test.js
  src/__tests__/components/table/PanelHeader.test.js
  src/__tests__/components/table/Table.test.js
  src/__tests__/components/user-requests/UserRequests.test.js
  src/__tests__/redux/ErrorReducer.test.js
  src/__tests__/redux/RequestsReducer.test.js
  src/__tests__/redux/actions/RequestActions.test.js
  src/__tests__/redux/reducers/ErrorReducer.test.js
  src/__tests__/redux/reducers/RequestsReducer.test.js
  src/components/admin-requests/AdminRequests.js
  src/components/table/PanelHeader.js
  src/components/table/PanelHeader.scss
  src/components/table/index.js
  src/components/user-requests/UserRequests.js
  src/redux/actions/RequestActions.js
  src/redux/actions/actionType.jsx
  src/redux/reducers/RequestsReducer.js
  src/styles/index.scss
Labels: ready for review

#26 #168049952 User Role Settings UI
  package-lock.json
  package.json
  src/__tests__/components/role-settings/RoleSetting.test.js
  src/__tests__/redux/actions/LoginAction.test.js
  src/__tests__/redux/actions/roleAction.test.js
  src/__tests__/redux/reducers/roleReducer.test.js
  src/assets/ic_create_white.svg
  src/components/Router.js
  src/components/index.js
  src/components/role-settings/RoleSettings.js
  src/components/role-settings/RoleSettings.scss
  src/components/side-bar/index.js
  src/components/side-bar/sidebar.scss
  src/redux/actions/actionType.js
  src/redux/actions/getRooms.js
  src/redux/actions/loginAction.js
  src/redux/actions/registerAction.js
  src/redux/actions/roleAction.js
  src/redux/reducers/roleReducer.js
  src/redux/reducers/rootReducer.js
Labels: ready for review

#25 #168049960 a user should be able to search requests
  package-lock.json
  src/__tests__/components/table/PanelHeader.test.js
  src/__tests__/components/user-requests/UserRequests.test.js
  src/assets/arrow_down.svg
  src/components/search-box/SearchBox.jsx
  src/components/search-box/SearchBox.scss
  src/components/side-bar/sidebar.scss
  src/components/table/PanelHeader.js
  src/components/table/PanelHeader.scss
  src/components/user-requests/UserRequests.js
  src/redux/actions/actionType.js
  src/redux/reducers/RequestsReducer.js
  src/redux/reducers/rootReducer.js
Labels: ready for review

#27 #168049956 Profile Information from Travel Request Page(UI)
  package.json
  src/__tests__/components/login-page/LoginPage.test.js
  src/__tests__/components/request-page/RequestPage.test.js
  src/components/form/form.jsx
  src/components/login-page/LoginPage.js
  src/components/request-page/RequestPage.jsx
  src/components/request-page/RequestPage.scss
  src/components/side-bar/index.js
  src/components/side-bar/sidebar.scss
  src/components/single-request/SingleRequest.jsx
  src/components/single-request/SingleRequest.scss
  src/redux/actions/RequestActions.js
  src/redux/actions/actionType.js
  src/redux/reducers/RequestsReducer.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/registerReducer.js
Labels: ready for review

#20 #168049955 Users should be able to comment on Travel Request
  .eslintrc.json
  package-lock.json
  package.json
  src/__tests__/components/admin-requests/AdminRequests.test.js
  src/__tests__/components/comment/Comment.test.js
  src/__tests__/components/login-page/LoginPage.test.js
  src/__tests__/components/login-page/SocialLogins.test.js
  src/__tests__/components/passwordReset/forgotEmailForm.test.js
  src/__tests__/components/passwordReset/resetPassword.test.js
  src/__tests__/components/register-page/registerPage.test.js
  src/__tests__/components/request-page/RequestPage.test.js
  src/__tests__/components/user-requests/UserRequests.test.js
  src/__tests__/redux/actions/CommentAction.test.js
  src/__tests__/redux/actions/registerAction.test.js
  src/__tests__/redux/reducers/CommentReducer.test.js
  src/assets/ic_account_circle.svg
  src/assets/ic_delete.svg
  src/assets/ic_send.svg
  src/components/Router.js
  src/components/admin-requests/AdminRequests.js
  src/components/comment/Comment.js
  src/components/comment/Comment.scss
  src/components/form/form.jsx
  src/components/index.js
  src/components/input/input.jsx
  src/components/passwordReset/forgotEmailForm.jsx
  src/components/passwordReset/resetPassword.jsx
  src/components/profile-page/ProfilePage.js
  src/components/request-page/RequestPage.jsx
  src/components/single-request/SingleRequest.css
  src/components/single-request/SingleRequest.css.map
  src/components/single-request/SingleRequest.jsx
  src/components/single-request/SingleRequest.scss
  src/components/table/Table.scss
  src/components/user-requests/UserRequests.js
  src/redux/actions/actionType.js
  src/redux/actions/commentAction.js
  src/redux/actions/passwordResetAction.js
  src/redux/actions/registerAction.js
  src/redux/actions/socialAuthAction.js
  src/redux/reducers/commentReducer.js
  src/redux/reducers/rootReducer.js
  src/services/history.js
  src/styles/App.scss
Labels: ready for merge

#24 #168049972 Add a view of accommodations
  .env.example
  package-lock.json
  package.json
  src/__mocks__/fixtures.js
  src/__mocks__/mockStore.js
  src/__tests__/components/accommodation/AccommodationsPage.test.js
  src/__tests__/components/accommodation/AnAccommodationPage.test.js
  src/__tests__/components/shared/modal/Modal.test.js
  src/__tests__/components/shared/modal/RequestActinModal.test.js
  src/__tests__/redux/actions/roleAction.test.js
  src/assets/images/svg/sprite.svg
  src/components/Router.js
  src/components/accommodation/AccommodationList.js
  src/components/accommodation/AccommodationsPage.js
  src/components/accommodation/AnAccommodationPage.js
  src/components/accommodation/RoomList.js
  src/components/index.js
  src/components/shared/map/MapContainer.js
  src/redux/actions/accommodatinsAction.js
  src/redux/actions/actionType.js
  src/redux/actions/roleAction.js
  src/redux/reducers/accommodationsReducer.js
  src/redux/reducers/rootReducer.js
  src/redux/store/initialState.js
  src/services/accommodationServices.js
  src/styles/_variables.scss
  src/styles/accommodations.scss
Labels: ready for review

#29 #168049977,#168049978 Trips stats and most visited destintations
  package-lock.json
  src/__tests__/components/dashboard/Dashboard.test.js
  src/__tests__/components/tripStat/mostTravelled.test.js
  src/__tests__/components/tripStat/singleTrip.test.js
  src/__tests__/components/tripStat/tripStats.test.js
  src/__tests__/redux/RequestsReducer.test.js
  src/__tests__/redux/actions/RequestActions.test.js
  src/assets/nbi_image.jpg
  src/components/Router.js
  src/components/dashboard/Dashboard.js
  src/components/dashboard/dashboard.scss
  src/components/form/form.jsx
  src/components/profile-page/Input.js
  src/components/table/index.js
  src/components/tripStats/mostTravelled.jsx
  src/components/tripStats/singleTrip.jsx
  src/components/tripStats/tripStats.jsx
  src/components/tripStats/tripStats.scss
  src/redux/actions/RequestActions.js
  src/redux/actions/actionType.js
  src/redux/reducers/RequestsReducer.js
  src/redux/reducers/initialState.js
  src/services/requestServices.js
Labels: ready for review
